<?php

namespace Database\User;

use Database\User\om\BaseUser;


/**
 * Skeleton subclass for representing a row from the 'media_library_user_users' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Mon Jun 22 15:48:00 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.User
 */
class User extends BaseUser
{
}
