<?php

namespace Database\Media;

use Database\Media\om\BaseGenre;


/**
 * Skeleton subclass for representing a row from the 'media_library_media_genre' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Mon Jun 22 15:48:01 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class Genre extends BaseGenre
{
}
